name: Docker
description: Runs your build steps in Docker containers
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    add-host:
      type: array
    additional-groups:
      type: array
    always-pull:
      type: boolean
    cap-add:
      type: array
    cap-drop:
      type: array
    command:
      type: array
    cpus:
      type: string
    debug:
      type: boolean
    devices:
      type: array
    entrypoint:
      type: [string, boolean]
    environment:
      type: array
    image:
      type: string
    init:
      type: boolean
    ipc:
      type: string
    mount-buildkite-agent:
      type: boolean
    mount-ssh-agent:
      type: boolean
    mount-checkout:
      type: boolean
    network:
      type: string
    privileged:
      type: boolean
    profile:
      type: string
    propagate-aws-auth-tokens:
      type: boolean
    propagate-environment:
      type: boolean
    propagate-uid-gid:
      type: boolean
    publish:
      type: array
    runtime:
      type: string
    shell:
      type: [boolean, array]
    shm-size:
      type: string
    tmpfs:
      type: array
    tty:
      type: boolean
    security-opt:
      type: array
    sysctls:
      type: array
    user:
      type: string
    userns:
      type: string
    volumes:
      type: array
    workdir:
      type: string
  required:
    - image
  additionalProperties: false
